/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomButton {
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary';
        /**
          * @default 'md'
         */
        "width": 'sm' | 'md' | 'lg';
    }
    interface MyCard {
        "content": string;
        "title": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyHeader {
    }
    interface MyLogin {
    }
}
declare global {
    interface HTMLCustomButtonElement extends Components.CustomButton, HTMLStencilElement {
    }
    var HTMLCustomButtonElement: {
        prototype: HTMLCustomButtonElement;
        new (): HTMLCustomButtonElement;
    };
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {
    }
    var HTMLMyHeaderElement: {
        prototype: HTMLMyHeaderElement;
        new (): HTMLMyHeaderElement;
    };
    interface HTMLMyLoginElement extends Components.MyLogin, HTMLStencilElement {
    }
    var HTMLMyLoginElement: {
        prototype: HTMLMyLoginElement;
        new (): HTMLMyLoginElement;
    };
    interface HTMLElementTagNameMap {
        "custom-button": HTMLCustomButtonElement;
        "my-card": HTMLMyCardElement;
        "my-component": HTMLMyComponentElement;
        "my-header": HTMLMyHeaderElement;
        "my-login": HTMLMyLoginElement;
    }
}
declare namespace LocalJSX {
    interface CustomButton {
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary';
        /**
          * @default 'md'
         */
        "width"?: 'sm' | 'md' | 'lg';
    }
    interface MyCard {
        "content"?: string;
        "title"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyHeader {
    }
    interface MyLogin {
    }
    interface IntrinsicElements {
        "custom-button": CustomButton;
        "my-card": MyCard;
        "my-component": MyComponent;
        "my-header": MyHeader;
        "my-login": MyLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-button": LocalJSX.CustomButton & JSXBase.HTMLAttributes<HTMLCustomButtonElement>;
            "my-card": LocalJSX.MyCard & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-header": LocalJSX.MyHeader & JSXBase.HTMLAttributes<HTMLMyHeaderElement>;
            "my-login": LocalJSX.MyLogin & JSXBase.HTMLAttributes<HTMLMyLoginElement>;
        }
    }
}
