'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { CustomButton as CustomButtonElement, defineCustomElement as defineCustomButton } from "stencil-demo/dist/components/custom-button.js";
import { MyCard as MyCardElement, defineCustomElement as defineMyCard } from "stencil-demo/dist/components/my-card.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "stencil-demo/dist/components/my-component.js";
import { MyHeader as MyHeaderElement, defineCustomElement as defineMyHeader } from "stencil-demo/dist/components/my-header.js";
import { MyLogin as MyLoginElement, defineCustomElement as defineMyLogin } from "stencil-demo/dist/components/my-login.js";

export type CustomButtonEvents = NonNullable<unknown>;

export const CustomButton: StencilReactComponent<CustomButtonElement, CustomButtonEvents> = /*@__PURE__*/ createComponent<CustomButtonElement, CustomButtonEvents>({
    tagName: 'custom-button',
    elementClass: CustomButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CustomButtonEvents,
    defineCustomElement: defineCustomButton
});

export type MyCardEvents = NonNullable<unknown>;

export const MyCard: StencilReactComponent<MyCardElement, MyCardEvents> = /*@__PURE__*/ createComponent<MyCardElement, MyCardEvents>({
    tagName: 'my-card',
    elementClass: MyCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyCardEvents,
    defineCustomElement: defineMyCard
});

export type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

export type MyHeaderEvents = NonNullable<unknown>;

export const MyHeader: StencilReactComponent<MyHeaderElement, MyHeaderEvents> = /*@__PURE__*/ createComponent<MyHeaderElement, MyHeaderEvents>({
    tagName: 'my-header',
    elementClass: MyHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyHeaderEvents,
    defineCustomElement: defineMyHeader
});

export type MyLoginEvents = NonNullable<unknown>;

export const MyLogin: StencilReactComponent<MyLoginElement, MyLoginEvents> = /*@__PURE__*/ createComponent<MyLoginElement, MyLoginEvents>({
    tagName: 'my-login',
    elementClass: MyLoginElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyLoginEvents,
    defineCustomElement: defineMyLogin
});
